-- CREATE TABLE
CREATE TABLE TBL_PRODUCT_AFFILIATE (
    PROD_ID serial PRIMARY KEY,
    PROD_TITLE VARCHAR(250),
    PROD_DESCRIPTION VARCHAR(1000),
    PROD_COMMISSION FLOAT(8),
    PROD_INIT_CONVERSION FLOAT(8),
    PROD_GRAVITY FLOAT(8),
    PROD_REBILL FLOAT(8),
    PROD_CATEGORY VARCHAR(250),
    PROD_LINK VARCHAR(100)
);
